### ISSUE TITLE
Unexpected interaction

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor-commandpalette#18]
When I click on an item, then use the down arrow to select the next item, I expect to be able to hit "enter" to select the new item.

**Comment by sccolbert** [comment]
I'm on the fence about what we should do after clicking an item. In most normal cases, I would expect the command palette to be closed. For cases where it's left open, one could reasonably expect the search to be cleared, so you can start with a fresh search. Happy to brainstorm about this.

**Comment by blink1073** [comment]
I'd prefer the search to be cleared.

**Comment by sccolbert** [comment]
We should also emit a signal when we execute a command, so an external controller can hide the palette if they want.

**Comment by sccolbert** [comment]
fixed in #26 

Triggering an item cause the query to be selected so the next keystroke starts a new search.
