### ISSUE TITLE
Expose action to clear buffer.

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor-commandpalette#19]
I would like to bind `Ctrl+U` to clear the buffer to the left, for instance (standard emacs keybinding).

**Comment by sccolbert** [comment]
We have exposed the `inputNode`. So one could conceivably do:

```typescript
palette.inputNode.value = '';
palette.update();
```

Do you think we should expose some dedicated methods for this?

**Comment by blink1073** [comment]
No, that is fair.
