### ISSUE TITLE
Expose actions to select next, previous, next category, first in buffer, last in buffer

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor-commandpalette#21]
These would all be very handy for power users.  For instance, I would bind `Ctrl+N` to "Move to Next Item" (standard Emacs shortcut).

**Comment by blink1073** [comment]
This command should be shared across the application, since I would want to use the same shortcut in the palette as the file browser.

**Comment by blink1073** [comment]
Ref:
https://github.com/jupyter/jupyter-js-filebrowser/blob/master/src/browser.ts#L257
https://github.com/jupyter/jupyter-js-filebrowser/blob/master/example/src/index.ts#L101

**Comment by sccolbert** [comment]
When you say `next` and `previous`, do you mean skipping headers?

**Comment by blink1073** [comment]
No, the equivalent of hitting the up and down arrow.

**Comment by sccolbert** [comment]
oh. Why not just use up/down?

**Comment by sccolbert** [comment]
In any case, I can see the use for having functions to control select next/previous command/header/either

**Comment by blink1073** [comment]
Muscle memory, I use Ctrl+P/N in every application.  It was especially helpful when I had to use 3 or 4 different keyboard layouts in a given day not to have to hunt for up/down.

**Comment by sccolbert** [comment]
got it

**Comment by sccolbert** [comment]
fix in #26
